job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/saymopronex/DevOps_MasterClass_Jenkins_Upgradev3.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', '/var/lib/jenkins/workspace/First_Maven_Project/maven-samples/single-module')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
